LearningManagementSytem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('login/', views.login_call),
    path('logout/', views.logout_call),
    path('signup/', views.signup),
    path('contactus/', views.contactus),
    path('student/', include('student.urls')),
    path('instructor/', include('instructor.urls'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instructor/urls.py
from django.urls import path
from . import views

app_name = 'instructor'

urlpatterns = [
    path('dashboard/', views.tech_dashboard),
    path('manage_courses/<int:id>/', views.manage_course, name="manage_course"),
    path('manage_lecture/<int:cid>/<int:id>', views.manage_lecture, name="manage_lecture"),
    path('lec_del/', views.lec_del),
    path('add_lecture/', views.add_lecture),
    path('edit_lecture/', views.edit_lecture),
    path('edit_course/', views.edit_course),
    path('profile/', views.up_profile),
    path('api/', views.CourseLecture.as_view())
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('dashboard/', views.stu_dashboard),
    path('add_cart/<int:id>/', views.add_cart, name='cart'),
    path('delcart/<int:id>/', views.del_cart, name="delcart"),
    path('courses/', views.stu_courses),
    path('profile/', views.up_profile),
    path('cartcalculate/', views.cartcalculate),
    path('filter/', views.filter),
    path('viewcourse/<int:id>/', views.view_course, name="viewcourse"),
    path('viewlecture/<int:cid>/<int:id>', views.view_lecture, name="viewlecture"),
    path('payment_history/', views.payment_history)
]

templates/add_course.html
{% extends "teacherdashboard.html" %}

{% load static %}

{% block 'homedata' %}
{% if messages %}
		{% for m in messages %}
		<script type="text/javascript"> alert("{{ m }}")</script>
		{% endfor %}
{% endif %}
<section id="center_course"></section>
<section id="mycourse">
    <div class="container">
        <div class="add_new_course">
            <div class="row">
                <div class="container con_sec">
                    <div class="col-sm-12">
                        <div class="row"
                            style="text-align: center; color: white; font-weight: 800; padding-bottom: 10px;">
                            <div class="col-sm-12">
                                <h2>{{ cou.title }}</h2>
                                <hr>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-1"></div>
                            <div class="col-sm-2">
                                <div class="input-group">
                                    <input type="search" class="form-control" placeholder="Search"
                                        aria-describedby="button-addon2" id="csearch">
                                    <button class="btn btn-primary" type="submit" id="button-addon2" disabled><i
                                            class="fas fa-search"></i></button>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <button class="btn btn-primary" type="buton" onclick="goBack()"><i class="fas fa-chevron-left"></i>&nbsp; Back</button>
                            </div>
                            <div class="col-sm-2">
                                <button class="btn btn-success" type="buton" data-bs-target="#edit_cou" data-bs-toggle="modal"><i class="fas fa-pencil-alt"></i>&nbsp; Edit Course</button>
                            </div>
                            <div class="col-sm-5">
                                <button class="btn btn-success val" data-bs-toggle="modal" data-bs-target="#add_lec"
                                    value="{{ i.id }}"><i class="fas fa-plus"></i>&nbsp; Add Lecture
                                </button>
                            </div>
                        </div>
                        <div class="row" style="padding:10px 0 20px 20px">
                            <!-- <p><span style="font-weight:700; font-size:medium;">Section :</span> &nbsp; {{i.title}} -->
                            <!-- </p> -->
                        </div>

                        <div class="row card-deck" style="margin: 30px;">
                            {% for j in lect %}
                            <div class="col-sm-11" style="background-color: transparent; border: none;">
                                <button class="btn " style="width: 100%; margin-bottom: 30px;"><a href="{% url 'instructor:manage_lecture' cid=cou.id id=j.id %}" id="disp">
                                    <div class="card " style="max-width: 100%; margin: 0%;" id="cardsearch">
                                        <div class="row no-gutters ">
                                            <div class="col-md-4 " style="margin: 0; background-color: black;">
                                                <video width="170px">
                                                    <source src="{{ j.video.url }}" type="video/mp4" alt="...">
                                                </video>
                                            </div>
                                            <div class="col-md-8" style=" background-color: rgba(128, 128, 128, 0.1);">
                                                <div class="card-body" style="text-align: left;">
                                                    <h5 class="card-title" style="color: green;"> Lecture: {{ j.title }}</h5>
                                                    <p class="card-text" style="color: grey; font-weight: 200;">{{ j.description }}</p>
                                                    <p class="card-text" style="font-weight: 100; margin-bottom: 0;">
                                                        <small class="text-muted">{{ j.dated }}</small>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </a></button>
                            </div>
                            <div class="col-sm-1 " style="margin-bottom: 30px; margin-right: 0;">
                                    <form method="POST" action="/instructor/lec_del/" style="width: 80%; height: 100%;" id="del">
                                        {% csrf_token %}
                                        <input type="hidden" value="{{ j.id }}" name="lecid">
                                        <input type="hidden" value="{{ cou.id }}" name="couid">
                                        <button class="btn btn-danger" type="submit" style=" width: 100%; height: 100%;"><i class="fas fa-trash-alt"></i></button>
                                    </form>
                            </div>
                            
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
{% endblock %}

{% block 'modall' %}
<div class="modal fade" id="add_lec" tabindex="-1" aria-labelledby="add_lecL" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="add_lecL">Select your course Category</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <form method="POST" action="/instructor/add_lecture/" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="contianer">
                                    <div class="form-row">
                                        <input type="text" name="title" class="form-control" placeholder="title"
                                            required>
                                    </div></br>
                                    <div class="form-row">
                                        <input type="text" name="descp" class="form-control" placeholder="Description"
                                            required>
                                    </div></br>
                                    <div class="form-row">
                                        <input type="file" name="vid" class="form-control" accept="video/mp4" required>
                                    </div></br>
                                    <input type="hidden" name="cid" value="{{ cou.id }}">
                                </div>
                            </div>
                        </div>
                </div>

            </div>
            <div class="modal-footer">
                <button class="new_practice" type="submit">
                    Add Lecture
                </button>
            </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="edit_cou" tabindex="-1" aria-labelledby="edit_cou" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="edit_cou">Edit your Course</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <form method="POST" action="/instructor/edit_course/" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="contianer">
                                    <div class="form-row">
                                        <textarea role="6" name="descp" class="form-control"
                                            required>{{ cou.description }}</textarea>
                                    </div></br>
                                    <div class="form-row">
                                        <input type="file" name="c_img" class="form-control" accept="image/jpg, image/png, image/jpeg" required>
                                    </div></br>
                                    <input type="hidden" name="cid" value="{{ cou.id }}">
                                </div>
                            </div>
                        </div>
                </div>

            </div>
            <div class="modal-footer">
                <button class="new_practice" type="submit">
                    Edit Course
                </button>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}


{% block 'usescript' %}
<script>
    $(document).ready(function () {

        jQuery.expr[':'].contains = function (a, i, m) {
            return jQuery(a).text().toUpperCase()
                .indexOf(m[3].toUpperCase()) >= 0;
        };
        $('#csearch').keyup(function () {
            $('.card').removeClass('d-none');
            var filter = $(this).val(); // get the value of the input, which we filter on
            $('.card-deck').find('.card .card-body h5:not(:contains("' + filter + '"))').parent().parent().parent().parent().addClass('d-none');
        });

        $("#del").submit(function(){
            var c = confirm("Are you Sure?");
            if(c == false){
                event.preventDefault();
            }
        });
    });

    function goBack(){
        window.history.back();
    }
</script>
{% endblock %}

templates/search.html
{% extends "teacherdashboard.html" %}

{% load static %}

{% block 'homedata' %}
<section id="center_course"></section>
<section id="search">
    <ul>
        {% for i in final %}
        <li>{{ i }}</li>
        {% endfor %}
    </ul>
</section>

{% endblock %}

templates/stu_course.html
{% extends "studentdashboard.html" %}

{% load static %}

{% block 'homedata' %}
<section id="center_course"></section>
<section id="course_stu">
    <div class="container">
        <div class="course_stu">

            <div class="row no-gutters">

                <div class="col-sm-3 course_stu_1">
                    <div class="container">
                        <div class="row">
                            <div class="input-group" style="padding:0;">
                                <input type="search" class="form-control" placeholder="Search" aria-describedby="button-addon2"
                                    id="csearch" name="csearch">
                                <button class="btn btn-primary" type="submit" id="button-addon2" disabled><i
                                        class="fas fa-search"></i></button>
                            </div>
                        </div>
                        <div class="row">
                            <form method="POST" action="/student/filter/">
                                {% csrf_token %}
                            <select class="form-select" name="filter" onchange="this.form.submit()"> 
                                <option selected>Level</option>
                                <option value="Beginner">Beginner</option>
                                <option value="Intermediate">Intermediate</option>
                                <option value="Expert">Expert</option>
                                <option value="All">All</option>
                            </select>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="col-sm-8 course_stu_2">
                    <div class="row card-deck">
                        {% for key, value in dict %}
                        {% if key.status == 'A' %}
                        <div class="card mb-3" style="max-width: 100%;">
                            <div class="row no-gutters">
                                <div class="col-md-4">
                                    <img src="{{ key.course_img.url }}" class="card-img" alt="..." width="100%">
                                </div>
                                <div class="col-md-6">
                                    <div class="card-body">
                                        <h5 class="card-title" style="color: green;">{{ key.title }}</h5>
                                        <p class="card-text">{{ key.description }}</p>
                                        <p class="card-text" style="font-size: small;">Level : {{ key.level }}</p>
                                        <p class="card-text"><small class="text-muted">Instructor: {{ value.first_name}}
                                                {{ value.last_name}}</small></p>
                                        <p class="card-text" style="color: #c2ae2a;">Price : {{ key.price }}</p>
                                        <p>
                                            <button class="btn btn-primary" style="margin-bottom: 0;">
                                                {% if key.id in optlistid %}
                                                <a style="text-decoration: none; font-weight: 200;" disabled>Opted</a>
                                                {% elif key.id not in cartlist %}
                                                <a a href="{% url 'student:cart' id=key.id %}" style="text-decoration: none; font-weight: 200;">Add to cart</a>
                                                {% else %}
                                                <a style="text-decoration: none; font-weight: 200;" disabled>Already Added</a>
                                                {% endif %}
                                            </button>
                                        </p>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/stu_filter.html
{% extends "studentdashboard.html" %}

{% load static %}

{% block 'homedata' %}
<section id="center_course"></section>
<section id="course_stu">
    <div class="container">
        <div class="course_stu">

            <div class="row no-gutters">

                <div class="col-sm-3 course_stu_1">
                    <div class="container">
                        <div class="row">
                            <div class="input-group" style="padding:0;">
                                <input type="search" class="form-control" placeholder="Search" aria-describedby="button-addon2"
                                    id="csearch" name="csearch">
                                <button class="btn btn-primary" type="submit" id="button-addon2" disabled><i
                                        class="fas fa-search"></i></button>
                            </div>
                        </div>
                        <div class="row">
                            <form method="POST" action="/student/filter/" style="width:100%">
                                {% csrf_token %}
                            <select class="form-select" name="filter" onchange="this.form.submit()"> 
                                <option selected>Level</option>
                                <option value="Beginner">Beginner</option>
                                <option value="Intermediate">Intermediate</option>
                                <option value="Expert">Expert</option>
                                <option value="All">All</option>
                            </select>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="col-sm-8 course_stu_2">
                    <div class="row card-deck">
                        {% for key, value in dict %}
                        {% if key.status == 'A' %}
                        <div class="card mb-3" style="max-width: 100%;">
                            <div class="row no-gutters">
                                <div class="col-md-4">
                                    <img src="{{ key.course_img.url }}" class="card-img" alt="..." width="100%">
                                </div>
                                <div class="col-md-6">
                                    <div class="card-body">
                                        <h5 class="card-title" style="color: green;">{{ key.title }}</h5>
                                        <p class="card-text">{{ key.description }}</p>
                                        <p class="card-text" style="font-size: small;">Level : {{ key.level }}</p>
                                        <p class="card-text"><small class="text-muted">Instructor: {{ value.first_name}}
                                                {{ value.last_name}}</small></p>
                                        <p class="card-text" style="color: #c2ae2a;">Price : {{ key.price }}</p>
                                        <p>
                                            <button class="btn btn-primary" style="margin-bottom: 0;">
                                                {% if key.id in optlistid %}
                                                <a style="text-decoration: none; font-weight: 200;" disabled>Opted</a>
                                                {% elif key.id not in cartlist %}
                                                <a a href="{% url 'student:cart' id=key.id %}" style="text-decoration: none; font-weight: 200;">Add to cart</a>
                                                {% else %}
                                                <a style="text-decoration: none; font-weight: 200;" disabled>Already Added</a>
                                                {% endif %}
                                            </button>
                                             <span class="price"></span>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/stu_paymenthistory.html
{% extends "studentdashboard.html" %}

{% load static  %}

{% block 'homedata' %}
<section id="center_course"></section>
<section id="mylearning">
    <div class="container">
        <div class="student_course">
            <div class="row">
                <div class="col-sm-12" style="text-align: center; color: white;">
                    <h2>PAYMENT HISTORY</h2>
                    <hr>
                </div>
            </div>
            <div class="row">
                <table class="table table-success table-striped">
                    <thead>
                      <tr>
                        <th scope="col">Order ID</th>
                        <th scope="col">Order Date</th>
                        <th scope="col">Course</th>
                        <th scope="col">Price</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Payment Method</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for key,value in or_dict %}
                      <tr>
                        <th scope="row">{{ key.order_id }}</th>
                        <td>{{ key.order_date }}</td>
                        <td>
                            <table class="table table-primary table-striped table-hover">
                                {% for j in value%}
                                <tr>
                                    <td>
                                        <a href="{% url 'student:viewcourse' id=j.id %}" style="text-decoration: none; font-weight: 100; color: black;">{{ j.title }}</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                        </td>
                        <td>
                            <table class="table table-primary table-striped">
                                {% for j in value%}
                                <tr>
                                    <td>{{ j.price }}</td>
                                </tr>
                                {% endfor %}
                            </table>
                        </td>
                        <td>{{ key.total_amt }}</td>
                        <td>{{ key.paid_by }}</td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/studentdashboard.html
{% extends "index.html" %}

{% load static %}

{% block 'navbar' %}
<section id="header">
    <nav class="navbar navbar-expand-lg fixed-top effect-3">
        <a class="navbar-brand" href="/student/dashboard/">E-LEARN <i class="fab fa-leanpub"></i></a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"
            aria-="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"><i class="fas fa-bars" style="color:#fff; font-size:28px;"></i></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 ">
                <li class="nav-item"><a class="nav-link" href="/student/dashboard/">My Learning</a></li>
                <li class="nav-item" style="padding-left: 20px;"><a class="nav-link"
                        href="/student/courses/">Courses</a></li>
                <li class="nav-item dropdown" style="padding-left: 20px;">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-shopping-cart"></i><span
                            class="badge .rounded-pill bg-dark" style="border-radius: 50%; font-size: 10px;">{{ cartlist | length }}</span>
                        <span class="visually-hidden">unread messages</span></a>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDarkDropdownMenuLink" style="padding: 5px 10px 0 10px; width: 250px; float: right; white-space: inherit;">
                        <form method="POST" action="/student/cartcalculate/">
                            {% csrf_token %}
                        <li class="scroll">
                            {% for i in items %}
                            <div class="card" style="width: 100%; margin: 0%; height: 180px;">
                                <input type="hidden" name="cid" value="{{ i.id }}">
                                <div class="row no-gutters">
                                    <div class="col-md-4" style="margin: 0;">
                                        <img src="{{ i.course_img.url }}" class="card-img" alt="..." width="100%" height="100%">
                                    </div>
                                    <div class="col-md-8">
                                        <div class="card-body" style="text-align: left;">
                                            <p class="card-title" style="color: green; font-size: 15px;">{{ i.title }}</p>
                                            <p style="color: #b6a015;">{{i.price}} 
                                               <a  href="{% url 'student:delcart' id=i.id %}" style="font-size: 12px;color: white !important; background-color: red; width: 20px;"><i class="fas fa-trash-alt"></i></a></span>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                       </li>
                       <li style="padding-bottom: 10px;">
                            <b>Total:</b>
                            <span style="float: right;">{{ total }}rs</span>
                            <input type="hidden" name="price" value="{{ total }}">
                       </li>
                       <li style="padding-bottom: 10px;">
                           <button class="btn btn-primary" type="submit" style="width: 100%;">Checkout</button>
                       </li>
                    </form>
                    </ul>
                </li>
                <li class="nav-item dropdown" style="padding-left: 20px;">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-user"></i></a>
                    <ul class="dropdown-menu .drop_1" aria-labelledby="navbarDarkDropdownMenuLink">
                        <li><a class="dropdown-item" href="/student/profile/">Account Setting</a></li>
                        <li><a class="dropdown-item" href="/student/payment_history/">Payment History</a></li>
                    </ul>
                </li>
                <li class="nav-item" style=" padding-left: 20px;"><a class="nav-link" href="/logout/"><i
                            class="fas fa-sign-out-alt"></i></a></li>
            </ul>
        </div>
    </nav>
</section>
{% endblock %}

{% block 'homedata' %}
<section id="center_course"></section>
<section id="mylearning">
    <div class="container">
        <div class="student_course">
            <div class="row">
                <div class="col-sm-12" style="text-align: center; color: white;">
                    <h2>MY LEARNING</h2>
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <div class="input-group">
                        <input type="search" class="form-control" placeholder="Search" aria-describedby="button-addon2"
                            id="csearch" name="csearch">
                        <button class="btn btn-primary" type="submit" id="button-addon2" disabled><i
                                class="fas fa-search"></i></button>
                    </div>
                </div>
                <div class="col-sm-2">
                </div>
            </div>


            <div class="row card-deck">
                {% for i in optlist %}
                <button class="btn"><a href="{% url 'student:viewcourse' id=i.id %}" id="disp">
                        <div class="card" style="max-width: 100%; margin: 0%;" id="cardsearch">
                            <div class="row no-gutters">
                                <div class="col-md-4" style="margin: 0;">
                                    <img src="{{ i.course_img.url }}" class="card-img" alt="..." height="170px"
                                        width="100%">
                                </div>
                                <div class="col-md-8" style=" background-color: rgba(128, 128, 128, 0.1);">
                                    <div class="card-body" style="text-align: left;">
                                        <h5 class="card-title" style="color: green;">{{ i.title }}</h5>
                                        <p class="card-text" style="color: grey; font-weight: 200;">{{ i.description }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a></button>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block 'modall' %}
{% endblock %}

{% block 'acc' %}
{% endblock %}

{% block 'learning'%}
{% endblock %}

{% block 'about'%}
{% endblock %}

{% block 'contactus'%}
{% endblock %}

{% block 'usescript' %}
<script>
    $(document).ready(function () {

        jQuery.expr[':'].contains = function (a, i, m) {
            return jQuery(a).text().toUpperCase()
                .indexOf(m[3].toUpperCase()) >= 0;
        };
        $('#csearch').keyup(function () {
            $('.card').removeClass('d-none');
            var filter = $(this).val(); // get the value of the input, which we filter on
            $('.card-deck').find('.card .card-body h5:not(:contains("' + filter + '"))').parent().parent().parent().parent().addClass('d-none');
        })

    });
</script>
{% endblock %}